=== csms-ethz/CombiFF/use/input_files/macro_replacements/replacements.dtd
<!ELEMENT replacements (replacement+)>
<!ATTLIST replacements version CDATA #REQUIRED>

<!ELEMENT replacement (macro,parameter)>

<!ELEMENT macro (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>

=== csms-ethz/CombiFF/use/input_files/macro_replacements/replacements.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE replacements SYSTEM "replacements.dtd">
<replacements version="1.0">
  <replacement>
    <macro>typ_CH4_ali.*</macro>
    <parameter>17</parameter>
  </replacement>
  <replacement>
    <macro>typ_CH3_ali.*</macro>
    <parameter>16</parameter>
  </replacement>
  <replacement>
    <macro>typ_CH2_ali.*</macro>
    <parameter>15</parameter>
  </replacement>
  <replacement>
    <macro>typ_CH1_ali.*</macro>
    <parameter>14</parameter>
  </replacement>
  <replacement>
    <macro>typ_C_ali.*</macro>
    <parameter>13</parameter>
  </replacement>
  <replacement>
    <macro>mass_CH4_ali.*</macro>
    <parameter>6</parameter>
  </replacement>
  <replacement>
    <macro>mass_CH3_ali.*</macro>
    <parameter>5</parameter>
  </replacement>
  <replacement>
    <macro>mass_CH2_ali.*</macro>
    <parameter>4</parameter>
  </replacement>
  <replacement>
    <macro>mass_CH1_ali.*</macro>
    <parameter>3</parameter>
  </replacement>
  <replacement>
    <macro>mass_C_ali.*</macro>
    <parameter>12</parameter>
  </replacement>
  <replacement>
    <macro>chg_CH4_ali.*</macro>
    <parameter>0.00000</parameter>
  </replacement>
  <replacement>
    <macro>chg_CH3_ali.*</macro>
    <parameter>0.00000</parameter>
  </replacement>
  <replacement>
    <macro>chg_CH2_ali.*</macro>
    <parameter>0.00000</parameter>
  </replacement>
  <replacement>
    <macro>chg_CH1_ali.*</macro>
    <parameter>0.00000</parameter>
  </replacement>
  <replacement>
    <macro>chg_C_ali.*</macro>
    <parameter>0.00000</parameter>
  </replacement>
  <replacement>
    <macro>bnd_C.*-C.*</macro>
    <parameter>27</parameter>
  </replacement>
  <replacement>
    <macro>ang_C.*-C.*-C.*</macro>
    <parameter>15</parameter>
  </replacement>
  <replacement>
    <macro>ang_C.*#C.*-C.*</macro>
    <parameter>55</parameter>
  </replacement>
  <replacement>
    <macro>imp_C.*-C.*-C.*-C.*</macro>
    <parameter>2</parameter>
  </replacement>
  <replacement>
    <macro>dih_C.*-C.*-C.*-C.*</macro>
    <parameter>34</parameter>
  </replacement>
</replacements>
