=== csms-ethz/CombiFF/use/output_files/molecule_decompositions/molecule_decompositions.dtd
<!ELEMENT molecule_decompositions (molecule_decomposition+)>
<!ATTLSIT molecule_decompositions family_code CDATA #IMPLIED tbl_version CDATA #REQUIRED>

<!ELEMENT molecule_decomposition (fragments,linkages)>
<!ATTLIST molecule_decomposition isomer_id CDATA #IMPLIED smiles CDATA #IMPLIED>

<!ELEMENT fragments (fragment+)>
<!ELEMENT fragment (#PCDATA)>
<!ATTLIST fragment id CDATA #REQUIRED>

<!ELEMENT linkages (linkage+)>
<!ELEMENT linkage (involved_fragment,involved_fragment)>

<!ELEMENT involved_fragment (fragment_id,linksite)>
<!ELEMENT fragment_id (#PCDATA)>
<!ELEMENT linksite (#PCDATA)>

=== csms-ethz/CombiFF/use/output_files/molecule_decompositions/molecule_decompositions_0100.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE molecule_decompositions SYSTEM "molecule_decompositions.dtd">
<molecule_decompositions enu_version="1.0" family_code="0100" family_version="1.0" tbl_version="1.0">
  <molecule_decomposition isomer_id="0100_000000001" smiles="C">
    <fragments>
      <fragment id="f1">~CH4</fragment>
    </fragments>
    <linkages></linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000002" smiles="CC">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
      </linkage>
    </linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000003" smiles="CCC">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
      <fragment id="f3">~CH2</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
      </linkage>
    </linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000004" smiles="CC(C)C">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
      <fragment id="f3">~CH3</fragment>
      <fragment id="f4">~CH1</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l3</linksite>
        </involved_fragment>
      </linkage>
    </linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000005" smiles="CCCC">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
      <fragment id="f3">~CH2</fragment>
      <fragment id="f4">~CH2</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
    </linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000006" smiles="CC(C)(C)C">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
      <fragment id="f3">~CH3</fragment>
      <fragment id="f4">~CH3</fragment>
      <fragment id="f5">~C_ali</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l3</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l4</linksite>
        </involved_fragment>
      </linkage>
    </linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000007" smiles="CCC(C)C">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
      <fragment id="f3">~CH3</fragment>
      <fragment id="f4">~CH2</fragment>
      <fragment id="f5">~CH1</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l3</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
    </linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000008" smiles="CCCCC">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
      <fragment id="f3">~CH2</fragment>
      <fragment id="f4">~CH2</fragment>
      <fragment id="f5">~CH2</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f4</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
    </linkages>
  </molecule_decomposition>
  <molecule_decomposition isomer_id="0100_000000009" smiles="CCC(C)(C)C">
    <fragments>
      <fragment id="f1">~CH3</fragment>
      <fragment id="f2">~CH3</fragment>
      <fragment id="f3">~CH3</fragment>
      <fragment id="f4">~CH3</fragment>
      <fragment id="f5">~CH2</fragment>
      <fragment id="f6">~C_ali</fragment>
    </fragments>
    <linkages>
      <linkage>
        <involved_fragment>
          <fragment_id>f1</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f5</fragment_id>
          <linksite>l1</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f2</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f6</fragment_id>
          <linksite>l2</linksite>
        </involved_fragment>
      </linkage>
      <linkage>
        <involved_fragment>
          <fragment_id>f3</fragment_id>
          <linksite>l</linksite>
        </involved_fragment>
        <involved_fragment>
          <fragment_id>f6</fragment_id>
