=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions.dtd
<!ELEMENT family_definitions (family_definition+)>
<!ATTLIST family_definitions version CDATA #REQUIRED>

<!ELEMENT family_definition (formula, (unsaturations|substructures|maximum_bond_degree|double_bonds|single_bonds|total_bonds|aromatic_bonds|triple_bonds|cycles)*)>
<!ATTLIST family_definition code CDATA #REQUIRED>

<!ELEMENT formula (#PCDATA)>
<!ELEMENT unsaturations (#PCDATA)>
<!ELEMENT substructures (substructure+)>
<!ELEMENT double_bonds (#PCDATA)>
<!ELEMENT single_bonds (#PCDATA)>
<!ELEMENT total_bonds (#PCDATA)>
<!ELEMENT aromatic_bonds (#PCDATA)>
<!ELEMENT triple_bonds (#PCDATA)>
<!ELEMENT cycles (#PCDATA)>

<!ELEMENT substructure (atoms)>
<!ATTLIST substructure substructure_code CDATA #REQUIRED amount CDATA #REQUIRED repetition (xor|and|or) #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT atoms (atom+)>
<!ELEMENT amount (#PCDATA)>

<!ELEMENT atom EMPTY>
<!ATTLIST atom type CDATA #REQUIRED>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_07xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    formaldehyde
  -->
  <family_definition code="0700">
    <formula>'C=O'1 H2</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="H"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C2-C10 aldehyde - 1 group
  -->
  <family_definition code="0701">
    <formula>C[0-8] 'CC(=O)H'1 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C2-C10 aldehyde - 2 groups
  -->
  <family_definition code="0702">
    <formula>C[0-8] 'C(H)=O'2 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="2">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C2-C10 aldehyde - 3 groups
  -->
  <family_definition code="0703">
    <formula>C[0-7] 'C(H)=O'3 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="3">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C2-C10 aldehyde - 4 groups
  -->
  <family_definition code="0704">
    <formula>C[0-6] 'C(H)=O'4 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="4">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_06xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one ketone group
  -->
  <family_definition code="0600">
    <formula>C[0-9] 'C=O'1 H[1-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" amount="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with two ketone groups
  -->
  <family_definition code="0601">
    <formula>C[0-8] 'C=O'2 H[1-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" amount="2">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with three ketone groups
  -->
  <family_definition code="0602">
    <formula>C[0-7] 'C=O'3 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" amount="3">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with four ketone groups
  -->
  <family_definition code="0603">
    <formula>C[0-6] 'C=O'4 H[1-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" amount="4">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_02xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!--
    linear and branched haloalkanes with C1 with up to 4 of the same Halos
  -->
  <family_definition code="0200">
    <formula>C1 H* Hal[1-4]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!--
    linear and branched haloalkanes with C1 with up to 4 Halos
  -->
  <family_definition code="0201">
    <formula>C1 H* Hal1 Hal[0-1] Hal[0-1] Hal[0-1]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!--
    linear and branched haloalkanes from C2 to C4 with up to 3 of the same Halos
  -->
  <family_definition code="0202">
    <formula>C[2-4] H* Hal[1-3]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!--
    linear and branched haloalkanes from C2 to C4 with 1-2 halos of one type and 1-2 halos of another type
  -->
  <family_definition code="0203">
    <formula>C[2-4] ^Hal[1-2] ^Hal[1-2] H*</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!--
    linear and branched haloalkanes from C2 to C4 with up to 1 halo of one type and 3 halos of another type
  -->
  <family_definition code="0204">
    <formula>C[2-4] H* ^Hal1 ^Hal3</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!--
    secondary monohaloalkanes with 5 C
  -->
  <family_definition code="0205">
    <formula>C5 H* Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TET" number="1">
        <atoms>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
          <atom type="Hal"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!--
    tertiary monohaloalkanes with 5 to 6 C
  -->
  <family_definition code="0206">
    <formula>C[5-6] H* Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TET" number="1">
        <atoms>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="Hal"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!--
    tertiary homohaloalkanes with 5 C with 1 to 3 halos
  -->
  <family_definition code="0207">
    <formula>C5 H* Hal[1-3]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TET" number="1">
        <atoms>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="CH3"/>
          <atom type="CH3"/>
          <atom type="CH3"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!--
    tertiary monohaloalkanes with 6 C with 1 to 2 halos
  -->
  <family_definition code="0208">
    <formula>C6 H* Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TET" number="1">
        <atoms>
          <atom type="C"/>
          <atom type="CH3"/>
          <atom type="CH3"/>
          <atom type="CH3"/>
          <atom type="CH1"/>
        </atoms>
      </substructure>
      <substructure substructure_code="TERNARY" number="1">
        <atoms>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="Hal"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!--
    linear and branched haloalkanes from C5 to C10 with up to 3 Halos
  -->
  <family_definition code="0209">
    <formula>C[5-10] H* Hal[1-3]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!--
    linear and branched haloalkanes from C5 to C9 with 1-2 halos of one type and 1-2 halos of another type
  -->
  <family_definition code="0210">
    <formula>C[5-9] H* ^Hal[1-2] ^Hal[1-2]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!--
    linear and branched haloalkanes from C5 to C9 with 1 halo of one type and 3 halo of another type
  -->
  <family_definition code="0211">
    <formula>C[5-9] H* ^Hal1 ^Hal3</formula>
    <unsaturations>0</unsaturations>
  </family_definition>  
  <!--
    linear and branched haloalkanes with C10 with 2 different Halos
  -->
  <family_definition code="0212">
    <formula>C10 H* ^Hal1 ^Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>  
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_08xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    C1-C10 1-ester family
  -->
  <family_definition code="0800">
    <formula>C[1-9] 'OC(=O)H'1 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    C1-C10 1-ester group (except methanoate)
  -->
  <family_definition code="0801">
    <formula>C[0-9] 'CH0=O'1 {OH0}1 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    C1-C10 2-ester groups
  -->
  <family_definition code="0802">
    <formula>C[0-8] 'OC(=O)H'2 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="2">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    C1-C10 2-ester group (except methanoate)
  -->
  <family_definition code="0803">
    <formula>C[0-8] 'CH0=O'2 {OH0}2 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="2">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    C1-C10 3-ester groups
  -->
  <family_definition code="0804">
    <formula>C[0-7]{CH1}3H[0-22]{OH0}6</formula>
    <unsaturations>3</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="3">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    C1-C10 3-ester groups (except methanoate)
  -->
  <family_definition code="0805">
    <formula>C[0-7] 'CH0=O'3 {OH0}3 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="3">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    C1-C10 4-ester groups
  -->
  <family_definition code="0806">
    <formula> C[0-6] 'OC(=O)H'4 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="4">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    C1-C10 4-ester groups (except methanoate)
  -->
  <family_definition code="0807">
    <formula>C[0-6] 'CH0=O'4 {OH0}4 H[0-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="4">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_04xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one alcohol group
  -->
  <family_definition code="0400">
    <formula>C[1-10] {OH}1 H[1-22]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with two alcohol groups
  -->
  <family_definition code="0401">
    <formula>C[1-10] {OH}2 H[1-22]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with three alcohol groups 
  -->
  <family_definition code="0402">
    <formula>C[1-10] {OH}3 H[1-22]</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_03xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!--
    benzenes with 6 subsitutents from {H, Halo, {CH3}}
  -->
  <family_definition code="0300">
    <formula>C6 {CH3}[0-6] H[0-6] Cl[0-6] Br[0-6] F[0-6] I[0-6]</formula>
    <unsaturations>4</unsaturations>
    <cycles>1</cycles>
    <double_bonds>3</double_bonds>
    <max_bond_degree>2</max_bond_degree>
    <substructures>
      <substructure substructure_code="BENZENE" number="1">
        <atoms>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_12xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one primary amide group
  -->
  <family_definition code="1200">
    <formula>'C=O'1 C[0-9] N1 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="AMIDE" amount="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="N"/>
          <atom type="H"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one secondary amide group
  -->
  <family_definition code="1201">
    <formula>'C=O'1 C[0-9] N1 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="AMIDE" amount="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="N"/>
          <atom type="H"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one tertiary amide group
  -->
  <family_definition code="1202">
    <formula>'C=O'1 C[0-9] N1 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="AMIDE" amount="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="N"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with two amide groups
  -->
  <family_definition code="1203">
    <formula>'C=O'2 C[0-8] N2 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="AMIDE" amount="2">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="N"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_14xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one P(R)(R)R group
  -->
  <family_definition code="1400">
    <formula>C[0-10] H[1-23] P1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with one P(OR)(R)R group
  -->
  <family_definition code="1401">
    <formula>C[0-10] H[1-23] O1 P1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="P"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with P(=O)(R)(R)R group
  -->
  <family_definition code="1404">
    <formula>C[0-10] H[1-23] 'Pf=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="Pf"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with P(=O)(OR)(R)R group
  -->
  <family_definition code="1405">
    <formula>C[0-10] H[1-23] O1 'Pf=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="Pf"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one P(OR)(OR)R group
  -->
  <family_definition code="1416">
    <formula>C[0-10] H[1-23] O2 P1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="P"/>
          <atom type="CorH"/>
          <atom type="O"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one P(OR)(OR)OR group
  -->
  <family_definition code="1417">
    <formula>C[0-10] H[1-23] O3 P1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="P"/>
          <atom type="O"/>
          <atom type="O"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with P(=O)(OR)(OR)R group
  -->
  <family_definition code="1422">
    <formula>C[0-10] H[1-23] O2 'Pf=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="Pf"/>
          <atom type="CorH"/>
          <atom type="O"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with P(=O)(OR)(OR)OR group
  -->
  <family_definition code="1423">
    <formula>C[0-10] H[1-23] O3 'Pf=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="Pf"/>
          <atom type="O"/>
          <atom type="O"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>
