=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions.dtd
<!ELEMENT family_definitions (family_definition+)>
<!ATTLIST family_definitions version CDATA #REQUIRED>

<!ELEMENT family_definition (formula, (unsaturations|substructures|maximum_bond_degree|double_bonds|single_bonds|total_bonds|aromatic_bonds|triple_bonds|cycles)*)>
<!ATTLIST family_definition code CDATA #REQUIRED>

<!ELEMENT formula (#PCDATA)>
<!ELEMENT unsaturations (#PCDATA)>
<!ELEMENT substructures (substructure+)>
<!ELEMENT double_bonds (#PCDATA)>
<!ELEMENT single_bonds (#PCDATA)>
<!ELEMENT total_bonds (#PCDATA)>
<!ELEMENT aromatic_bonds (#PCDATA)>
<!ELEMENT triple_bonds (#PCDATA)>
<!ELEMENT cycles (#PCDATA)>

<!ELEMENT substructure (atoms)>
<!ATTLIST substructure substructure_code CDATA #REQUIRED amount CDATA #REQUIRED repetition (xor|and|or) #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT atoms (atom+)>
<!ELEMENT amount (#PCDATA)>

<!ELEMENT atom EMPTY>
<!ATTLIST atom type CDATA #REQUIRED>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_09xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    formic acid family
  -->
  <family_definition code="0900">
    <formula>'C(=O)OH'1 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="H"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    carboxylic acid family
  -->
  <family_definition code="0901">
    <formula>C[1-9] 'C(=O)OH'1 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="H"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    carboxylic acid family - 2 groups
  -->
  <family_definition code="0902">
    <formula>C[0-8] 'C(=O)OH'2 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="2">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="H"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    carboxylic acid family - 3 groups
  -->
  <family_definition code="0903">
    <formula>C[0-7] 'C(=O)OH'3 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="3">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="H"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    carboxylic acid family - 3 groups
  -->
  <family_definition code="0904">
    <formula>C[0-6] 'C(=O)OH'4 H*</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="4">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="H"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_05xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one ether group
  -->
  <family_definition code="0500">
    <formula>C[1-10] {OH0}1 H[1-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ETHER" number="1">
        <atoms>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with two ether groups
  -->
  <family_definition code="0501">
    <formula>C[1-10] {OH0}2 H[1-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ETHER" number="2">
        <atoms>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with three ether groups
  -->
  <family_definition code="0502">
    <formula>C[1-10] {OH0}3 H[1-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ETHER" number="3">
        <atoms>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with four ether groups
  -->
  <family_definition code="0503">
    <formula>C[1-10] {OH0}4 H[1-22]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ETHER" number="4">
        <atoms>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/.family_definitions_10xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one amine group
  -->
  <family_definition code="1000">
    <formula>C[1-10] N1 H[1-40]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="N"/>
          <atom type="C"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one primary amine group
  -->
  <family_definition code="1001">
    <formula>C[1-10] N1 H[1-40]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="N"/>
          <atom type="C"/>
          <atom type="H"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one secondary amine group
  -->
  <family_definition code="1002">
    <formula>C[1-10] N1 H[1-40]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="N"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one tertiary amine group
  -->
  <family_definition code="1003">
    <formula>C[1-10] N1 H[1-40]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="1">
        <atoms>
          <atom type="N"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with two amine group
  -->
  <family_definition code="1004">
    <formula>C[1-10] N2 H[1-40]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="2">
        <atoms>
          <atom type="N"/>
          <atom type="C"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with three amine groups
  -->
  <family_definition code="1005">
    <formula>C[1-10] N3 H[1-40]</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="TERNARY" amount="3">
        <atoms>
          <atom type="N"/>
          <atom type="C"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_11xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one alcohol group and 1 halogen
  -->
  <family_definition code="1100">
    <formula>C[1-6] H[1-22] {OH}1 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C6 with one alcohol group and 2 halogens
  -->
  <family_definition code="1101">
    <formula>C[1-6] H[1-22] {OH}1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C6 with one alcohol group and 3 halogens
  -->
  <family_definition code="1102">
    <formula>C[1-6] H[1-22] {OH}1 Hal1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C6 with one alcohol group and 4 halogens
  -->
  <family_definition code="1103">
    <formula>C[1-6] H[1-22] {OH}1 Hal1 Hal1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with 2 alcohol groups and 1 halogen
  -->
  <family_definition code="1104">
    <formula>C[1-6] H[1-22] {OH}2 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with 2 alcohol groups and 2 halogens
  -->
  <family_definition code="1105">
    <formula>C[1-6] H[1-22] {OH}2 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with 2 alcohol groups and 3 halogens
  -->
  <family_definition code="1106">
    <formula>C[1-6] H[1-22] {OH}2 Hal1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with 2 alcohol groups and 4 halogens
  -->
  <family_definition code="1107">
    <formula>C[1-6] H[1-22] {OH}2 Hal1 Hal1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with 1 ketone group and 1 halogen
  -->
  <family_definition code="1108">
    <formula>C[1-7] H[0-20] 'C=O'1 Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with 1 ketone group and 2 halogens
  -->
  <family_definition code="1109">
    <formula>C[1-7] H[0-20] 'C=O'1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with 1 ketone group and 3 halogens
  -->
  <family_definition code="1110">
    <formula>C[1-7] H[0-20] 'C=O'1 Hal1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with 1 aldehyde group and 1 halogen
  -->
  <family_definition code="1111">
    <formula>C[0-6] 'CC(=O)H'1 H[0-22]  Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with 1 aldehyde group and 2 halogens
  -->
  <family_definition code="1112">
    <formula>C[0-6] 'CC(=O)H'1 H[0-22] Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with 1 aldehyde group and 3 halogens
  -->
  <family_definition code="1113">
    <formula>C[0-6] 'CC(=O)H'1 H[0-22] Hal1 Hal1 Hal1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="H"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C2-C10 - 1 ketone + 1 ester
  -->
  <family_definition code="1128">
    <formula>C[0-8] H[0-22] 'C=O'2 {OH0}1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
      <substructure substructure_code="ESTER" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C2-C10 - 1 ether + 1 ester
  -->
  <family_definition code="1130">
    <formula>C[3-9] H[0-24] {OH0}2 'CH0=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C2-C10 - 1 ester + 1 formate
  -->
  <family_definition code="1147">
    <formula>C[0-8] H[0-24] 'CH0=O'1 {OH0}1 'OC(=O)H'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="ESTER" number="2" repetition="xor">
        <atoms>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="O"/>
          <atom type="C"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_tests.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    benzene test family:
     - for C5 NoP1 H2 Hal2 Hal1: 432
     - for C5 N1 {CH3}2 Hal2 Hal1 : 216
     - for C6 SB1 SB1 SB1 SB1 SB1 SB1 : 4291
     - for C6 ^SB1 ^SB1 ^SB1 ^SB1 ^SB1 ^SB1 : 60
  -->
  <family_definition code="test_benzene">
    <formula>C6 ^SB1 ^SB1 ^SB1 ^SB1 ^SB1 ^SB1</formula>
    <double_bonds>3</double_bonds>
    <substructures>
      <substructure substructure_code="BENZENE" number="1">
        <atoms>
          <atom type="*"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
          <atom type="C"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <family_definition code="double_bond">
    <formula>C[2-5]H[0-20]</formula>
    <double_bonds>1</double_bonds>
    <unsaturations>1</unsaturations>
  </family_definition>
  <family_definition code="double_bond_halo">
    <formula>C[2-3]H[0-12]F[0-12]Br[0-12]</formula>
    <double_bonds>1</double_bonds>
    <unsaturations>1</unsaturations>
  </family_definition>
  <family_definition code="cycles">
    <formula>C6H[0-20]F1Br1</formula>
    <cycles>1</cycles>
    <unsaturations>1</unsaturations>
  </family_definition>
</family_definitions>

=== csms-ethz/CombiFF/use/input_files/family_definitions/family_definitions_13xx.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE family_definitions SYSTEM "family_definitions.dtd">
<family_definitions version="1.0">
  <!-- 
    saturated C1-C10 with one sulfur group
  -->
  <family_definition code="1300">
    <formula>C[0-10] H[1-22] S2</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="NBUTYL" number="1">
        <atoms>
          <atom type="CorH"/>
          <atom type="S"/>
          <atom type="S"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one S(=O)(R)(R) group
  -->
  <family_definition code="1311">
    <formula>C[0-10] H[1-22] O1 Sf1</formula>
    <unsaturations>1</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="Sf"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with one S(=O)(OR)(R) group
  -->
  <family_definition code="1312">
    <formula>C[0-10] H[1-22] O2 Sf1</formula>
    <unsaturations>1</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="Sf"/>
          <atom type="O"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with S(=O)(=O)(R)R group
  -->
  <family_definition code="1314">
    <formula>C[0-10] H[1-22] 'Ss(=O)=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="SULFONYL" number="1">
        <atoms>
          <atom type="Ss"/>
          <atom type="O"/>
          <atom type="O"/>
          <atom type="CorH"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with S(=O)(=O)(OR)R group
  -->
  <family_definition code="1315">
    <formula>C[0-10] H[1-22] O1 'Ss(=O)=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="SULFONYL" number="1">
        <atoms>
          <atom type="Ss"/>
          <atom type="O"/>
          <atom type="O"/>
          <atom type="O"/>
          <atom type="CorH"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with S(=O)(=O)(OR)R group
  -->
  <family_definition code="1326">
    <formula>C[0-10] H[1-22] O2 'Ss(=O)=O'1</formula>
    <unsaturations>0</unsaturations>
    <substructures>
      <substructure substructure_code="SULFONYL" number="1">
        <atoms>
          <atom type="Ss"/>
          <atom type="O"/>
          <atom type="O"/>
          <atom type="O"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
  <!-- 
    saturated C1-C10 with two sulfer groups
  -->
  <family_definition code="1323">
    <formula>C[0-10] H[1-22] S1</formula>
    <unsaturations>0</unsaturations>
  </family_definition>
  <!-- 
    saturated C1-C10 with one S(=O)(OR)(OR) group
  -->
  <family_definition code="1324">
    <formula>C[0-10] H[1-22] O3 Sf1</formula>
    <unsaturations>1</unsaturations>
    <substructures>
      <substructure substructure_code="KETONE" number="1">
        <atoms>
          <atom type="O"/>
          <atom type="Sf"/>
          <atom type="O"/>
          <atom type="O"/>
        </atoms>
      </substructure>
    </substructures>
  </family_definition>
</family_definitions>
